main:
  - identifier: about
    name: L'association
    url: /about/
    weight: 20
  - identifier: ateliers
    pre: complexdropdown
    name: Ateliers
    weight: 30
  - identifier: mediatheque
    name: Médiathèque
    url: /mediatheque/
    weight: 35
  - identifier: cml
    name: Les Savanturiers (Multisports)
    url: /club-multisports/
    weight: 37
  - identifier: events
    pre: complexdropdown
    name: Événements
    weight: 40
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 50
ateliers:

  - identifier: cirque
    pre: /images/logos/gym.svg
    name: Renforcement musculaire
    post: Lundi avec Alice
    url: /ateliers/cirque/
    weight: 20
  - identifier: cirque-enfant
    pre: /images/logos/cirque.svg
    name: Cirque Enfant
    post: Mercerdi avec Alice
    url: /ateliers/cirque-enfant/
    weight: 21
  - identifier: yoga
    pre: /images/logos/yoga.svg
    name: Yoga
    post: Lundi, Mercredi & Jeudi avec Antonine
    url: /ateliers/yoga/
    weight: 30
  - identifier: gym
    pre: /images/logos/gym.svg
    name: Gym
    post: Lundi avec Monique
    url: /ateliers/gym/
    weight: 31
  - identifier: theatre-adultes
    pre: /images/logos/theatre.svg
    name: Théâtre adultes
    post: Vendredi avec Alain
    url: /ateliers/theatre-adultes/
    weight: 40
  - identifier: theatre-ado
    pre: /images/logos/theatre.svg
    name: Dessin 
    post: jeeu avec Isabelle
    url: /ateliers/dessin/
    weight: 50
  - identifier: sophrologie
    pre: /images/logos/sophrologie.svg
    name: Sophrologie
    post: Lundi avec Aurélie
    url: /ateliers/sophrologie/
    weight: 60
  - identifier: memoire
    pre: /images/logos/brain.svg
    name: Mémoire
    post: Mardi avec Nathalie
    url: /ateliers/memoire/
    weight: 70
events:
  - identifier: hivernale
    pre: /images/logos/vtt.svg
    name: L'hivernale
    post: Randonnée VTT
    url: /evenements/hivernale
    weight: 10
  - identifier: trail
    pre: /images/logos/running.svg
    name: Lyricantrail
    post: Course nature de 14 et 26km
    url: /evenements/lyricantrail
    weight: 20
  - identifier: festibaleine
    pre: /images/logos/baleine.svg
    name: Festi'Baleine
    post: Festival de Musique
    url: /evenements/baleine
    weight: 30
  - identifier: triathlon
    pre: /images/logos/triathlon.svg
    name: Triathlon
    post: Grimpe, VTT, trail (les années paires)
    url: /evenements/triathlon
    weight: 40
  - identifier: conferences
    pre: /images/logos/conference.svg
    name: Conférences
    post: Ouvertes à tous et toutes
    url: /evenements/conferences
    weight: 50
  - identifier: foire
    pre: /images/logos/plante.svg
    name: Foire aux plantes
    post: Botanique et vie locale
    url: /evenements/foire-aux-plantes
    weight: 60
  - identifier: vide-grenier
    pre: /images/logos/market.svg
    name: Vide Grenier
    post: (les années impaires)
    url: /evenements/vide-grenier
    weight: 70
  - identifier: telethon
    pre: /images/logos/tele.svg
    name: Telethon
    post: AFM Téléthon
    url: /evenements/telethon
    weight: 80
footer:
  - identifier: about
    name: L'association
    url: /about/
    weight: 10
  - identifier: blog
    name: Blog
    url: /posts/
    weight: 20
  - identifier: news
    name: News
    url: /news/
    weight: 30
  - identifier: ateliers
    name: Les ateliers
    url: /ateliers/
    weight: 40
  - identifier: events
    name: Les événements
    url: /evenements/
    weight: 45
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 50
